package com.miketheshadow.ouchmybones;

public enum InjuryType {

    BLINDNESS,ONE_LEGGED,LEGLESS,BROKEN_LEG,
    MISSING_ARM_RIGHT,MISSING_ARM_LEFT, BROKEN_ARM_RIGHT,BROKEN_ARM_LEFT,
    BROKEN_BACK,HEADACHE,CONCUSSION,MAIMED

}
